name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: twt898xu/vuepress-blog@main
      env:
        ACCESS_TOKEN: ${{ secrets.VUEPRESS_BLOG }}
        TARGET_REPO: twt898xu/twt898xu.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm ci && npm run build
        BUILD_DIR: docs/.vuepress/dist
        COMMIT_MESSAGE:  Auto deploy by the Vuepress-deploy